### ISSUE TITLE
Fails to import PDF document

### ISSUE THREAD

**Issue by arky** [SamEdwardes/spacypdfreader#12]
Unable to import this PDF document using spacypdfreader. The import results in high cpu usage and caused the system to hang.

https://docs.aiddata.org/ad4/pdfs/Banking_on_the_Belt_and_Road_Executive_Summary.pdf

**Comment by SamEdwardes** [comment]
Can you please provide a reproducible example and include the output?

**Comment by arky** [comment]
@SamEdwardes Here is simple testcase I have used. https://gist.github.com/arky/c91d20a8769846aec32262c76eea815d The issue surfaces when you are processing a pdf with large number of pages.  
The program runs forever taking all available CPU.

**Comment by SamEdwardes** [comment]
Thank you @arky. Is there any way you are able to share the specific code and output related to the issue? Your gist refers to "test.pdf", and the PDF you shared in your first message is 3 pages.

**Comment by arky** [comment]
@SamEdwardes I was able to reproduce the error using the following file as test-case 
Code snippet: https://gist.github.com/arky/c91d20a8769846aec32262c76eea815d
Test-case: https://docs.aiddata.org/ad4/pdfs/Banking_on_the_Belt_and_Road_Executive_Summary.pdf
However any PDF with sufficiently large number of pages should be able to generate similar problems. 

Unfortunately I wasn't able to reproduce any debug logs as the process becomes unresponsive.

**Comment by arky** [comment]
Thank you @SamEdwardes for doing the research. Perhaps for now adding a note about correctly handling large sized documents could be added into the documentation.

**Comment by arky** [comment]
@SamEdwardes Touching base to see if we could resolve this issue either with implementation of multiprocessing or by expanding the docs as stop-gap measure. 

Thanks!

**Comment by SamEdwardes** [comment]
@arky thank you for the reminder! I can make an update to the docs today!

**Comment by arky** [comment]
@SamEdwardes You are most welcome, please let me know if I could help in any way.

**Comment by arky** [comment]
Thank you @SamEdwardes
